using UnityEngine;

public class Pickup : MonoBehaviour
{
    public ItemData itemData; // Informaci칩n del objeto
    private bool isPlayerNearby = false; 
    public GameObject pickupText; 

    void Update()
    {
        if (isPlayerNearby && Input.GetKeyDown(KeyCode.E))
        {
            CollectItem();
        }
    }

    void OnTriggerEnter(Collider other)
    {
        if (other.CompareTag("Player"))
        {
            isPlayerNearby = true;
            pickupText.SetActive(true); 
        }
    }

    void OnTriggerExit(Collider other)
    {
        if (other.CompareTag("Player"))
        {
            isPlayerNearby = false;
            pickupText.SetActive(false);
        }
    }


    void CollectItem()
    {
        InventoryManager inventoryManager = FindObjectOfType<InventoryManager>(); // Encuentra el InventoryManager
        if (inventoryManager != null)
        {
            inventoryManager.AddItem(itemData); // A침ade el objeto al inventario
            Debug.Log($"{itemData.itemName} recogido y a침adido al inventario.");
            Destroy(gameObject); 
            pickupText.SetActive(false); 
        }
        else
        {
            Debug.LogError("No se encontr칩 el InventoryManager en la escena.");
        }
    }

}
